-- ============================================================
-- Лабораторная работа №3: БД educationDB
-- Создание базы данных и заполнение тестовыми данными
-- ============================================================

-- Запуск: psql -U postgres -f setup_db.sql

-- Удалить БД если существует (отключить активные соединения)
SELECT pg_terminate_backend(pid) FROM pg_stat_activity
WHERE datname = 'educationDB' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS "educationDB";
CREATE DATABASE "educationDB"
    ENCODING = 'UTF8'
    LC_COLLATE = 'ru_RU.UTF-8'
    LC_CTYPE = 'ru_RU.UTF-8'
    TEMPLATE = template0;

\c "educationDB"

-- ============================================================
-- 0. ENUM-тип единиц измерения
-- ============================================================
CREATE TYPE public.unit AS ENUM ('кг', 'л', 'шт');

-- ============================================================
-- 1. Таблица "Branch_office" (Филиалы)
-- ============================================================
CREATE TABLE "Branch_office" (
    number       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) COLLATE "C" NOT NULL,
    region       TEXT COLLATE "C" NOT NULL UNIQUE,
    locality     TEXT COLLATE "C" NOT NULL,
    address      TEXT NOT NULL,
    opening_date DATE NOT NULL,
    phone        TEXT NOT NULL
                 CONSTRAINT "Branch_office_phone_check"
                 CHECK (phone SIMILAR TO '[+][7][0-9]{10}'),
    "director's name"  TEXT,
    "director's photo" BYTEA
);

-- ============================================================
-- 2. Таблица "Shop" (Магазины)
-- ============================================================
CREATE TABLE "Shop" (
    number         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    locality       TEXT NOT NULL,
    street         TEXT NOT NULL,
    home           VARCHAR(6) NOT NULL,
    phone          TEXT UNIQUE
                   CONSTRAINT "Shop_phone_check"
                   CHECK (phone SIMILAR TO '[+][7][0-9]{10}'),
    open           BIT(1) NOT NULL,
    openning_date  DATE NOT NULL,
    number_office  INTEGER NOT NULL
                   REFERENCES "Branch_office"(number)
                   ON UPDATE CASCADE
                   ON DELETE CASCADE
);

-- ============================================================
-- 3. Таблица "Product" (Продукты)
--    category — категория из фиксированного списка,
--    name     — произвольное наименование (опционально).
-- ============================================================
CREATE TABLE "Product" (
    number   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL
             CONSTRAINT "Product_category_check"
             CHECK (category IN ('сахар', 'мука', 'масло', 'молоко', 'хлеб', 'другое')),
    units    public.unit NOT NULL,
    name     TEXT
);

-- ============================================================
-- 4. Таблица "Shop_Product" (Товары в магазинах)
-- ============================================================
CREATE TABLE "Shop_Product" (
    num_product     INTEGER NOT NULL
                    REFERENCES "Product"(number)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,
    num_shop        INTEGER NOT NULL
                    REFERENCES "Shop"(number)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,
    quantity        INTEGER NOT NULL DEFAULT 0
                    CONSTRAINT "Shop_Product_quantity_check"
                    CHECK (quantity >= 0),
    price_per_unit  MONEY NOT NULL DEFAULT 0.00
                    CONSTRAINT "Shop_Product_price_per_unit_check"
                    CHECK (price_per_unit >= 0::money),
    revenue_for_the_prod MONEY GENERATED ALWAYS AS
                    (quantity * price_per_unit) STORED,
    PRIMARY KEY (num_product, num_shop)
);

-- ============================================================
-- 5. VIEW: полный адрес магазина + название филиала
-- ============================================================
CREATE OR REPLACE VIEW shop_full_info AS
SELECT
    s.number,
    s.name,
    s.locality || ', ' || s.street || ', д. ' || s.home AS full_address,
    s.phone,
    s.open,
    s.openning_date,
    b.name AS branch_name
FROM "Shop" s
LEFT JOIN "Branch_office" b ON s.number_office = b.number;

-- ============================================================
-- 6. Тестовые данные
-- ============================================================

-- Филиалы
INSERT INTO "Branch_office" (name, region, locality, address, opening_date, phone, "director's name")
VALUES
    ('Томский',     'Томская область',      'Томск',      'пр. Ленина, 40',         '2022-05-19', '+73822999999', 'Петров Ю.Д.'),
    ('Кемеровский', 'Кемеровская область',  'Кемерово',   'пр. Октябрьский, 33',    '2024-05-20', '+73842999999', NULL),
    ('Алтайский',   'Алтайский край',       'Барнаул',    'пр. Комсомольский, 70',  '2025-02-01', '+73852111222', 'Маркова М.Г.');

-- Магазины
INSERT INTO "Shop" (name, locality, street, home, phone, open, openning_date, number_office)
VALUES
    ('Продукты 24',     'Томск',     'пр. Ленина',      '10',   '+79001112233', B'1', '2022-06-01', 1),
    ('Мини-маркет',     'Томск',     'ул. Герцена',     '5',    '+79002223344', B'1', '2022-08-15', 1),
    ('Супермаркет',     'Кемерово',  'ул. Кирова',      '30',   '+79003334455', B'1', '2024-08-01', 2),
    ('Эконом-лавка',    'Кемерово',  'пр. Советский',   '100',  '+79004445566', B'0', '2024-10-20', 2),
    ('У дома',          'Барнаул',   'пр. Ленина',      '7',    '+79005556677', B'1', '2025-03-01', 3);

-- Продукты (category + name)
INSERT INTO "Product" (category, units, name)
VALUES
    ('сахар',  'кг', 'Сахар-песок'),
    ('мука',   'кг', 'Мука пшеничная высший сорт'),
    ('масло',  'кг', 'Масло сливочное 82,5%'),
    ('молоко', 'л',  'Молоко 3,2%'),
    ('хлеб',   'шт', 'Хлеб «Дарницкий»'),
    ('другое', 'шт', 'Яйца C1, десяток');

-- Товары в магазинах.
-- Цены задаём числовыми литералами (numeric → money), а не строками,
-- чтобы парсинг не зависел от lc_monetary текущей сессии (с локалью
-- ru_RU.UTF-8 строка '89.90'::money не парсится).
INSERT INTO "Shop_Product" (num_product, num_shop, quantity, price_per_unit)
VALUES
    (1, 1,  50,   89.90),
    (2, 1,  30,   65.50),
    (3, 1,  20,  150.00),
    (4, 1, 100,   79.90),
    (5, 1, 200,   45.00),
    (6, 1,  40,  120.00),
    (1, 2,  25,   92.00),
    (4, 2,  60,   82.50),
    (5, 2,  80,   48.00),
    (1, 3, 100,   85.00),
    (2, 3,  70,   60.00),
    (3, 3,  40,  145.00),
    (4, 3, 150,   75.00),
    (5, 3, 300,   42.00),
    (2, 4,  15,   70.00),
    (5, 4,  50,   50.00),
    (1, 5,  30,   90.00),
    (3, 5,  10,  155.00),
    (4, 5,  45,   80.00);

-- Проверка
SELECT '=== Филиалы ===' AS info;
SELECT * FROM "Branch_office";

SELECT '=== Магазины ===' AS info;
SELECT * FROM "Shop";

SELECT '=== Продукты ===' AS info;
SELECT * FROM "Product";

SELECT '=== Товары в магазинах ===' AS info;
SELECT * FROM "Shop_Product";

SELECT '=== VIEW: shop_full_info ===' AS info;
SELECT * FROM shop_full_info;
