-- ============================================================
-- Лабораторная работа №3: БД educationDB
-- Создание базы данных и заполнение тестовыми данными
-- ============================================================

-- Запуск: psql -U postgres -f setup_db.sql

-- Удалить БД если существует (отключить активные соединения)
SELECT pg_terminate_backend(pid) FROM pg_stat_activity
WHERE datname = 'educationDB' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS "educationDB";
CREATE DATABASE "educationDB"
    ENCODING = 'UTF8'
    LC_COLLATE = 'ru_RU.UTF-8'
    LC_CTYPE = 'ru_RU.UTF-8'
    TEMPLATE = template0;

\c "educationDB"

-- ============================================================
-- 1. Таблица "Branch_office" (Филиалы)
-- ============================================================
CREATE TABLE "Branch_office" (
    number      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    region      TEXT NOT NULL UNIQUE,
    locality    TEXT NOT NULL,
    address     TEXT NOT NULL,
    opening_date DATE NOT NULL,
    phone       TEXT NOT NULL
                CONSTRAINT "Branch_office_phone_check"
                CHECK (phone ~ '^\+[0-9]{11}$'),
    "director's name"  TEXT,
    "director's photo"  BYTEA
);

-- ============================================================
-- 2. Таблица "Shop" (Магазины)
-- ============================================================
CREATE TABLE "Shop" (
    number         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    locality       TEXT NOT NULL,
    street         TEXT NOT NULL,
    home           TEXT NOT NULL,
    phone          TEXT
                   CONSTRAINT "Shop_phone_check"
                   CHECK (phone ~ '^\+[0-9]{11}$'),
    open           BIT(1) NOT NULL,
    openning_date  DATE NOT NULL,
    number_office  INTEGER NOT NULL
                   REFERENCES "Branch_office"(number)
                   ON UPDATE RESTRICT
                   ON DELETE RESTRICT
);

-- ============================================================
-- 3. Таблица "Product" (Продукты)
-- ============================================================
CREATE TABLE "Product" (
    number  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name    VARCHAR(6) NOT NULL
            CONSTRAINT "Product_name_check"
            CHECK (name IN ('сахар', 'мука', 'масло', 'молоко', 'хлеб')),
    units   VARCHAR(2) NOT NULL
            CONSTRAINT "Product_units_check"
            CHECK (units IN ('кг', 'л', 'шт'))
);

-- ============================================================
-- 4. Таблица "Shop_Product" (Товары в магазинах)
-- ============================================================
CREATE TABLE "Shop_Product" (
    num_product     INTEGER NOT NULL
                    REFERENCES "Product"(number),
    num_shop        INTEGER NOT NULL
                    REFERENCES "Shop"(number),
    quantity        INTEGER NOT NULL DEFAULT 0
                    CONSTRAINT "Shop_Product_quantity_check"
                    CHECK (quantity >= 0),
    price_per_unit  MONEY NOT NULL DEFAULT 0.00
                    CONSTRAINT "Shop_Product_price_per_unit_check"
                    CHECK (price_per_unit >= 0::money),
    revenue_for_the_prod MONEY GENERATED ALWAYS AS
                    (quantity * price_per_unit) STORED,
    PRIMARY KEY (num_product, num_shop)
);

-- ============================================================
-- 5. VIEW: полный адрес магазина + название филиала
-- ============================================================
CREATE OR REPLACE VIEW shop_full_info AS
SELECT
    s.number,
    s.name,
    s.locality || ', ' || s.street || ', д. ' || s.home AS full_address,
    s.phone,
    s.open,
    s.openning_date,
    b.name AS branch_name
FROM "Shop" s
LEFT JOIN "Branch_office" b ON s.number_office = b.number;

-- ============================================================
-- 6. Тестовые данные
-- ============================================================

-- Филиалы
INSERT INTO "Branch_office" (name, region, locality, address, opening_date, phone, "director's name")
VALUES
    ('Филиал Центральный', 'Томская область', 'Томск', 'пр. Ленина, 10', '2020-03-15', '+79001234567', 'Иванов И.И.'),
    ('Филиал Северный', 'Новосибирская область', 'Новосибирск', 'ул. Кирова, 25', '2021-07-01', '+79009876543', 'Петров П.П.'),
    ('Филиал Восточный', 'Кемеровская область', 'Кемерово', 'ул. Советская, 5', '2022-01-10', '+79005551234', 'Сидоров С.С.');

-- Магазины
INSERT INTO "Shop" (name, locality, street, home, phone, open, openning_date, number_office)
VALUES
    ('Продукты 24',   'Томск',       'пр. Ленина',     '10',  '+79001112233', B'1', '2020-04-01', 1),
    ('Мини-маркет',   'Томск',       'ул. Герцена',    '5',   '+79002223344', B'1', '2020-06-15', 1),
    ('Супермаркет',   'Новосибирск', 'ул. Кирова',     '30',  '+79003334455', B'1', '2021-08-01', 2),
    ('Эконом-лавка',  'Новосибирск', 'ул. Красный пр.','100', '+79004445566', B'0', '2022-02-20', 2),
    ('Продукты у дома','Кемерово',   'ул. Советская',  '7',   '+79005556677', B'1', '2022-03-01', 3);

-- Продукты
INSERT INTO "Product" (name, units)
VALUES
    ('сахар', 'кг'),
    ('мука',  'кг'),
    ('масло', 'кг'),
    ('молоко','л'),
    ('хлеб',  'шт');

-- Товары в магазинах
INSERT INTO "Shop_Product" (num_product, num_shop, quantity, price_per_unit)
VALUES
    (1, 1, 50,  '89.90'),
    (2, 1, 30,  '65.50'),
    (3, 1, 20,  '150.00'),
    (4, 1, 100, '79.90'),
    (5, 1, 200, '45.00'),
    (1, 2, 25,  '92.00'),
    (4, 2, 60,  '82.50'),
    (5, 2, 80,  '48.00'),
    (1, 3, 100, '85.00'),
    (2, 3, 70,  '60.00'),
    (3, 3, 40,  '145.00'),
    (4, 3, 150, '75.00'),
    (5, 3, 300, '42.00'),
    (2, 4, 15,  '70.00'),
    (5, 4, 50,  '50.00'),
    (1, 5, 30,  '90.00'),
    (3, 5, 10,  '155.00'),
    (4, 5, 45,  '80.00');

-- Проверка
SELECT '=== Филиалы ===' AS info;
SELECT * FROM "Branch_office";

SELECT '=== Магазины ===' AS info;
SELECT * FROM "Shop";

SELECT '=== Продукты ===' AS info;
SELECT * FROM "Product";

SELECT '=== Товары в магазинах ===' AS info;
SELECT * FROM "Shop_Product";

SELECT '=== VIEW: shop_full_info ===' AS info;
SELECT * FROM shop_full_info;
